### ISSUE TITLE
Add example for 3-line kite

### ISSUE THREAD

**Issue by ufechner7** [aenarete/KiteViewers.jl#33]
Handling of a 3-line kite has been added to common.jl, but an example is missing.

For the 4point kite, the basic example looks like this:
```julia
using KiteViewers, KiteUtils
viewer=Viewer3D(true);
segments=6
state=demo_state_4p(segments+1)
update_system(viewer, state, kite_scale=0.25)
nothing
```
You can find the demo_state_4p function here: https://github.com/ufechner7/KiteUtils.jl/blob/ed15b4e482f7b9855343e92a2218e57bf25ab1e2/src/KiteUtils.jl#L308C1-L357C4

**Comment by 1-Bart-1** [comment]
Added an example here: https://github.com/aenarete/KiteViewers.jl/pull/34

In order to work the KiteUtils package has to be updated as well: https://github.com/ufechner7/KiteUtils.jl/pull/51

**Comment by ufechner7** [comment]
Example was provided: basic_4p_3lines.jl
